package View;

import static View.Login.isConnect;

public class home extends javax.swing.JFrame {

	  
    public home() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Home Vol");  
  Login login = new Login();
        jDesktopPane2.add(login);
        login.setVisible(true);


                }
        

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        btn_LogOut = new com.k33ptoo.components.KButton();
        btn_airport = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();
        btn_VolList = new com.k33ptoo.components.KButton();
        btn_ShowEscale = new com.k33ptoo.components.KButton();
        btn_ShowUsers1 = new com.k33ptoo.components.KButton();
  
        btn_Morder = new com.k33ptoo.components.KButton();

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
      
        jDesktopPane2 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(154, 164, 190));
        kGradientPanel1.setkGradientFocus(900);
        kGradientPanel1.setkStartColor(new java.awt.Color(104, 127, 184));//menuu
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseClicked(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
//logouuttt
        btn_LogOut.setBorder(null);
        btn_LogOut.setText("Sign out");
        btn_LogOut.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        btn_LogOut.setkBorderRadius(50);
        btn_LogOut.setkEndColor(new java.awt.Color(198, 83, 116));
        btn_LogOut.setkFillButton(false);
        btn_LogOut.setkHoverEndColor(new java.awt.Color(60, 33, 36));
        btn_LogOut.setkHoverForeGround(new java.awt.Color(0, 53, 04));
        btn_LogOut.setkHoverStartColor(new java.awt.Color(0, 2, 3));
        btn_LogOut.setkStartColor(new java.awt.Color(255, 255, 255));
        btn_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogOutActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 170, 40));

      
//show  airport 
        btn_airport.setBorder(null);
        btn_airport.setText("show airport");
        btn_airport.setkBorderRadius(50);
        btn_airport.setkEndColor(new java.awt.Color(198, 83, 116));
        btn_airport.setkFillButton(false);
        btn_airport.setkHoverEndColor(new java.awt.Color(60, 33, 36));
        btn_airport.setkHoverForeGround(new java.awt.Color(0, 53, 04));
        btn_airport.setkHoverStartColor(new java.awt.Color(0, 02, 3));
        btn_airport.setkStartColor(new java.awt.Color(255, 255, 255));
        btn_airport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_airportActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_airport, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 170, 40));
        
// image avion
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/volll.png"))); // NOI18N
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 160, 130));
// Vol listt
        btn_VolList.setBorder(null);
        btn_VolList.setText("Vol List");
        btn_VolList.setkBorderRadius(50);
        btn_VolList.setkEndColor(new java.awt.Color(198, 83, 116));
        btn_VolList.setkFillButton(false);
        btn_VolList.setkHoverEndColor(new java.awt.Color(60, 33, 36));
        btn_VolList.setkHoverForeGround(new java.awt.Color(0, 53, 04));
        btn_VolList.setkHoverStartColor(new java.awt.Color(0, 02, 3));
        btn_VolList.setkStartColor(new java.awt.Color(255, 255, 255));
        btn_VolList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btn_VolListActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_VolList, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 170, 40));
//escale
        btn_ShowEscale.setBorder(null);
        btn_ShowEscale.setText("Show escale");
        btn_ShowEscale.setkBorderRadius(50);
        btn_ShowEscale.setkEndColor(new java.awt.Color(198, 83, 116));
        btn_ShowEscale.setkFillButton(false);
        btn_ShowEscale.setkHoverEndColor(new java.awt.Color(60, 33, 36));
        btn_ShowEscale.setkHoverForeGround(new java.awt.Color(0, 53, 04));
        btn_ShowEscale.setkHoverStartColor(new java.awt.Color(0, 02, 3));
        btn_ShowEscale.setkStartColor(new java.awt.Color(255, 255, 255));
        btn_ShowEscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ShowEscaleActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_ShowEscale, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 170, 40));
        
        // make vol
        btn_Morder.setBorder(null);
        btn_Morder.setText( "Make Vol " );
        
        btn_Morder.setkBorderRadius(50);
        btn_Morder.setkEndColor(new java.awt.Color(198, 83, 116));
        btn_Morder.setkFillButton(false);
        btn_Morder.setkHoverEndColor(new java.awt.Color(60, 33, 36));
        btn_Morder.setkHoverForeGround(new java.awt.Color(0, 53, 04));
        btn_Morder.setkHoverStartColor(new java.awt.Color(0, 02, 3));
        btn_Morder.setkStartColor(new java.awt.Color(255, 255, 255));
        btn_Morder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MorderActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_Morder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 170, 40));
        
       //userrs
        btn_ShowUsers1.setBorder(null);
        btn_ShowUsers1.setText("Show Users");
        btn_ShowUsers1.setkBorderRadius(50);
        btn_ShowUsers1.setkEndColor(new java.awt.Color(198, 83, 116));
        btn_ShowUsers1.setkFillButton(false);
        btn_ShowUsers1.setkHoverEndColor(new java.awt.Color(60, 33, 36));
        btn_ShowUsers1.setkHoverForeGround(new java.awt.Color(0, 53, 04));
        btn_ShowUsers1.setkHoverStartColor(new java.awt.Color(0, 2, 3));
        btn_ShowUsers1.setkStartColor(new java.awt.Color(255, 255, 255));
        btn_ShowUsers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ShowUsers1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_ShowUsers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 170, 40));

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("      Gestion VoL ");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ZayerNayrez");
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 790, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/github-logo.png"))); // NOI18N
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 780, -1, -1));

       


        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 820));

        jDesktopPane2.setDesktopManager(null);
        getContentPane().add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1160, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogOutActionPerformed
if (isConnect==true){
        jDesktopPane2.removeAll();
          Login login = new Login();
        jDesktopPane2.add(login);
        login.setVisible(true);
          isConnect=false;
}
    }//GEN-LAST:event_btn_LogOutActionPerformed

    private void btn_ShowEscaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ShowEscaleActionPerformed
        //        jDesktopPane2.removeAll();
        if (isConnect==true){
           
      ShowEscale ShowEscale = new ShowEscale();
       jDesktopPane2.add(ShowEscale);
      ShowEscale.setVisible(true);
        }

    }//GEN-LAST:event_btn_ShowEscaleActionPerformed

    private void btn_MorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MorderActionPerformed
       if (isConnect==true){
        MakeVol Import = new MakeVol();
        jDesktopPane2.add(Import);
        Import.setVisible(true);
       }
    }//GEN-LAST:event_btn_MorderActionPerformed
  
    private void  btn_VolListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OrderListActionPerformed
        if (isConnect==true){
        ShowVol ShowVols = new ShowVol();
        jDesktopPane2.add(ShowVols);
        ShowVols.setVisible(true);
        }}

    private void btn_airportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_airportActionPerformed
        if (isConnect==true){
        ShowAirports Airport = new ShowAirports();
        jDesktopPane2.add(Airport);
        Airport.setVisible(true);
        }
    }//GEN-LAST:event_btn_airportActionPerformed

    private void btn_ShowUsers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ShowUsers1ActionPerformed
       if (isConnect==true){
        ShowUsers ShowUsers = new ShowUsers();
        jDesktopPane2.add(ShowUsers);
        ShowUsers.setVisible(true);
       }
    }//GEN-LAST:event_btn_ShowUsers1ActionPerformed

 
    private void kGradientPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseClicked

    }//GEN-LAST:event_kGradientPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.k33ptoo.components.KButton btn_airport;
    private com.k33ptoo.components.KButton btn_LogOut;
    public com.k33ptoo.components.KButton btn_VolList;
    public com.k33ptoo.components.KButton btn_Morder;

    public com.k33ptoo.components.KButton btn_ShowEscale;
    protected com.k33ptoo.components.KButton btn_ShowUsers1;
    public javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables

}
