/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.UserController;
import Model.User;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;

/**
 *
 * @author Iyed
 */
public class Login extends javax.swing.JInternalFrame {

    /**
     * Creates new form Login
     */
    public static boolean isConnect = false;
    public static boolean isAdmin = false;
    
    public Login() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new com.k33ptoo.components.KGradientPanel();
        jLabel10 = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        UserName = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_Cancel = new com.k33ptoo.components.KButton();
        btn_Connect = new com.k33ptoo.components.KButton();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Login.setkEndColor(new java.awt.Color(104, 127, 184 ));
        Login.setkGradientFocus(100);
        Login.setkStartColor(new java.awt.Color(104, 127, 184));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sign In");
        Login.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 90, -1));
//cadre login
        kGradientPanel1.setkBorderRadius(50);
        kGradientPanel1.setkEndColor(new java.awt.Color(239, 206, 238));
        kGradientPanel1.setkFillBackground(false);
        kGradientPanel1.setkGradientFocus(600);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 53, 53));
        kGradientPanel1.setOpaque(false);
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserName.setBackground(new Color (0,0,0,0));
        UserName.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        UserName.setForeground(new java.awt.Color(255, 255, 255));
        UserName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        UserName.setOpaque(false);
        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 310, 50));

        Password.setBackground(new Color(0,0,0,0));
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        Password.setOpaque(false);
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 320, 40));

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password");
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, -1));

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Login");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 90, -1));

        btn_Cancel.setBorder(null);
        btn_Cancel.setText("Cancel");
        btn_Cancel.setkBorderRadius(50);
        btn_Cancel.setkEndColor(new java.awt.Color(153, 153, 255));
        btn_Cancel.setkFillButton(false);
        btn_Cancel.setkHoverEndColor(new java.awt.Color(160, 133, 236));
        btn_Cancel.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_Cancel.setkHoverStartColor(new java.awt.Color(0, 2, 3));
        btn_Cancel.setkStartColor(new java.awt.Color(255, 255, 255));
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 170, 40));

        btn_Connect.setBorder(null);
        btn_Connect.setText("Connect");
        btn_Connect.setkBorderRadius(50);
        btn_Connect.setkEndColor(new java.awt.Color(153, 153, 255));
        btn_Connect.setkFillButton(false);
        btn_Connect.setkHoverEndColor(new java.awt.Color(160, 133, 236));
        btn_Connect.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_Connect.setkHoverStartColor(new java.awt.Color(0, 02, 3));
        btn_Connect.setkStartColor(new java.awt.Color(255, 255, 255));
        btn_Connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConnectActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_Connect, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 170, 40));

        Login.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 550, 380));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/user_s2c71luo9t9t_64.png"))); // NOI18N
        Login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
               

                
    }//GEN-LAST:event_UserNameActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed

    }//GEN-LAST:event_btn_CancelActionPerformed

    private void btn_ConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConnectActionPerformed
        String  login =  UserName.getText();
       String pwd =  String.valueOf(Password.getPassword());
        String Type ;
        
     
        UserController uc = new UserController();
        if(uc.connect(login, pwd)){              
            JOptionPane.showMessageDialog(this,
            "Connecté avec success "+ login.toUpperCase(),
            "Authentification", JOptionPane.INFORMATION_MESSAGE);

            this.setVisible(false);
            isConnect = true;

            
        }else{          
        JOptionPane.showMessageDialog(this,
            "Connection erronée "+ login.toUpperCase(),
            "Authentification", JOptionPane.ERROR_MESSAGE);
        }
       ArrayList<User>  myuserlist = new UserController().SelectByLoginPwd(login, pwd);
       for (User u : myuserlist)
       {
        Type = u.getType();
        System.out.println(Type);
       if("admin".equals(u.getType()))
       {isAdmin=true;}
       else{isAdmin=false;}
           }         
     
         System.out.println(isConnect);
         System.out.println(isAdmin);
  
   

    }//GEN-LAST:event_btn_ConnectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KGradientPanel Login;
    public javax.swing.JPasswordField Password;
    public javax.swing.JTextField UserName;
    private com.k33ptoo.components.KButton btn_Cancel;
    private static com.k33ptoo.components.KButton btn_Connect;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
