/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AirportController;
import Controller.VolController;
import Controller.EscaleController;
import Model.Airport;
import Model.Vol;
import Model.Escale;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;

import javax.swing.JTable;


/**
 *
 * @author Iyed
 */
public class MakeVol extends javax.swing.JInternalFrame {

    /**
     * Creates new form Import
     */
    public MakeVol() {
        initComponents();
         TxtVolId.setEnabled(false);
   

        ArrayList<Escale>   myEscaleList  = new EscaleController().retrieveAll();
        DefaultTableModel modelES = new DefaultTableModel() ;

        EscaleList.setModel(modelES) ; 
        modelES.addColumn("idEs");
        modelES.addColumn("heuredep");
        modelES.addColumn("heureArr");
        modelES.addColumn("AirportEs");
       
        for (Escale p :  myEscaleList ) {            
            Object[] row =   new Object[]{p.getidEs(), p.getheuredep(), p.getheureArr(),p.getAirportEs() };
            modelES.addRow(  row);
}
        EscaleList.setModel(modelES) ; 

        /////////////////////////////////////
        ArrayList<Airport>  myAirportlist = new AirportController().retrieveAll();
        for (Airport c  : myAirportlist) {            
            Object[] row =   new Object[]{c.getId(), c.getNameAirport(),c.getPaysAirport()};
       }
        
    }
    public void refresh()
    {
        TxtVolId.setText("");
     
        TxtheuredepEscale .setText("");
        TxtDdepVol.setText("");
        totallbl.setText("");
        datelbl.setText("");
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
       jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        EscaleList = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TxtheuredepEscale  = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabell20 = new javax.swing.JLabel();
        datelbl = new javax.swing.JTextField();
        heureEs= new javax.swing.JTextField();
        EscaleList = new javax.swing.JTable();

        TxtVolId = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtNameAirport =new javax.swing.JComboBox<>();
        
        jLabel15 = new javax.swing.JLabel();
        jLabel155 = new javax.swing.JLabel();

        TxtEscaleName = new javax.swing.JComboBox<>();
        TxtEscaleAirport = new javax.swing.JTextField();

        AddButn = new com.k33ptoo.components.KButton();
        AddButn1 = new com.k33ptoo.components.KButton();
        jLabel16 = new javax.swing.JLabel();
        totallbl = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TxtDdepVol = new javax.swing.JTextField();
        TxtDArrVol = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel199= new javax.swing.JLabel();

        jLabel20 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Import");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkGradientFocus(900);
        kGradientPanel1.setkStartColor(new java.awt.Color(15, 95, 134));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Make new Vol");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/money_bag_y8voit0gtqim_64.png"))); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, -1, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 110));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
////////
        
        
        
        
    

         EscaleList.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
         EscaleList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
         EscaleList.setDragEnabled(true);
         EscaleList.setOpaque(false);
         EscaleList.setSelectionBackground(new java.awt.Color(15, 95, 134));
         EscaleList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                 EscaleListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(EscaleList);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580,300, 520, 300));
  
        
        
        
        /////
     
   
        jLabel12.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("Vol Id");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        datelbl.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        datelbl.setForeground(new java.awt.Color(0, 153, 153));

        TxtVolId.setForeground(new java.awt.Color(204, 0, 51));
        jPanel1.add(TxtVolId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 120, 30));

        jLabel14.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("Airport départ:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));
        
        ArrayList<Airport>  myAirportlist = new AirportController().retrieveAll();

        List<String> airportNames = new ArrayList<>();

        for (Airport airport : myAirportlist) {
            airportNames.add(airport.getNameAirport());
        }

        // Create the default combo box model with the airport names list
        javax.swing.DefaultComboBoxModel<String> model = new javax.swing.DefaultComboBoxModel<>(airportNames.toArray(new String[0]));

        // Set the model to your JComboBox
       TxtNameAirport.setModel(model);
        
       TxtNameAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               TxtNameAirportActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNameAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 120, 30));

        jLabel15.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("Airport Arrivé:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));
        for (Airport airport : myAirportlist) {
            airportNames.add(airport.getNameAirport());
        }
        // Create the default combo box model with the airport names list
        javax.swing.DefaultComboBoxModel<String> model1 = new javax.swing.DefaultComboBoxModel<>(airportNames.toArray(new String[0]));

        // Set the model to your JComboBox
        TxtEscaleName.setModel(model1);
        TxtEscaleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	TxtEscaleNameActionPerformed(evt);
            }
        });
        //arport arrivé
        jPanel1.add(TxtEscaleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 120, 30));

//arport escale
		jLabel155.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel155.setForeground(new java.awt.Color(0, 153, 153));
        jLabel155.setText("Airport Escale :");
        jPanel1.add(jLabel155, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, -1, -1));
        jPanel1.add(TxtEscaleAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, 120, 30));

        
        AddButn.setText("Cancel");
        AddButn.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        AddButn.setkEndColor(new java.awt.Color(102, 204, 255));
        AddButn.setkHoverEndColor(new java.awt.Color(0, 102, 255));
        AddButn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        AddButn.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        AddButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButnActionPerformed(evt);
            }
        });
        jPanel1.add(AddButn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, -1, -1));

        AddButn1.setText("Add Vol");
        AddButn1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        AddButn1.setkEndColor(new java.awt.Color(102, 204, 255));
        AddButn1.setkHoverEndColor(new java.awt.Color(0, 102, 255));
        AddButn1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        AddButn1.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        AddButn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButn1ActionPerformed(evt);
            }
        });
        jPanel1.add(AddButn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, -1, -1));

 
        jLabel18.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 153));
        jLabel18.setText("<html>Date départ<br/>Vol:</html>");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        jPanel1.add(TxtDdepVol, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 120, 30));

        jLabel16.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 153));
        jLabel16.setText("<html>Date Arrivé <br/>Vol:</html>");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270,180, -1, -1));
        jPanel1.add(TxtDArrVol, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 120, 30));

     
        
        jLabel19.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("<html>heure départ<br/>Escale:</html>");
      jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550,180,-1,-1));
        jPanel1.add(datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(680,180,120,30));

        jLabel199.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel199.setForeground(new java.awt.Color(0, 153, 153));
        jLabel199.setText("<html>heure Arrivé <br/>Escale:</html>");
      jPanel1.add(jLabel199, new org.netbeans.lib.awtextra.AbsoluteConstraints(820,180,-1,-1));
        jPanel1.add(heureEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(950,180,120,30));
        
        jLabell20.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabell20.setForeground(new java.awt.Color(0, 153, 153));
        jLabell20.setText("<html>Réservation :</html>");
        jLabel20.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "true", "false" }));
        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        jLabel20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	 jLabel20ActionPerformed(evt);
            }
        });

        jPanel1.add(jLabell20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80,250,-1,-1));

        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200,250,-1,-1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1150, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

              
            
           
            
    private void AddButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButnActionPerformed
       refresh();     
    }//GEN-LAST:event_AddButnActionPerformed

    private void AddButn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButn1ActionPerformed
        Escale Escale = new Escale ();
        int x= EscaleList.getSelectedRow();
        int idEs = Integer.parseInt(""+EscaleList.getValueAt(x, 0));
        String heuredep = (String) EscaleList.getValueAt(x, 1);
        String heureArr= (String) EscaleList.getValueAt(x, 2); 
        String AirportEs =(String)EscaleList.getValueAt(x, 3);
        
        
        Vol Vol = new Vol();
     
        
        Vol.setNameAirport(TxtNameAirport.getSelectedItem().toString());
        
        Vol.setNameAirportArr(TxtEscaleName.getSelectedItem().toString());
        
        Vol.setAerportEscale(TxtEscaleAirport.getText());
        
        Vol.setDdepVol(TxtDdepVol.getText());
        Vol.setDarrVol(TxtDArrVol.getText());
        
        Vol.setHeureArrEscale(heureEs.getText());
        Vol.setHeuredepEscale(datelbl.getText());
        
        Vol.setReservation(jLabel20.getSelectedItem().toString());
     //   Vol.setReservation(jLabell20.getSelectedItem().toString());
        
        boolean result = new VolController().create(Vol);
       
       if(result){              
            JOptionPane.showMessageDialog(this,
            Vol.getIdVol()+" Is successfuly added  ",
            "New Vol", JOptionPane.INFORMATION_MESSAGE);
            //new userList().setVisible(true);
           
            refresh();
            
        }    
        ////////////////////////////////////////////////////////////////////////////////////
        
        
		Escale.setheuredep(heuredep);
        Escale.setheureArr(heureArr);
        Escale.setAirportEs( AirportEs);
       
        boolean result1 = new EscaleController().update(idEs, Escale);
         if(result1){              
            
            JOptionPane.showMessageDialog(this,
            Escale.getheuredep().toUpperCase()+" est modifié avec success ",
            "Modifier utilisateur", JOptionPane.INFORMATION_MESSAGE);
            
                    ArrayList<Escale>  EscaleList  = new EscaleController().retrieveAll();
            
                  

                    for (Escale pr : EscaleList ) {            
                        Object[] row =   new Object[]{pr.getidEs(), pr.getheuredep(), pr.getheureArr() , pr.getAirportEs() };
                    }
         }}
        
    //GEN-LAST:event_AddButn1ActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        //total();
    }//GEN-LAST:event_jLabel20MouseClicked
    private void jLabel20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void TxtNameAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirportitemsActionPerformed
        // TODO add your handling code here:
    }
    private void  TxtEscaleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirportitemsActionPerformed
        // TODO add your handling code here:
    }
   
 
    
    private void EscaleListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EscaleListMouseClicked
        int x= EscaleList .getSelectedRow();
        if(x == -1){
            JOptionPane.showMessageDialog(this,
                "Select row please !",
                "Information Message", JOptionPane.INFORMATION_MESSAGE);
        } else{

            int id = Integer.parseInt(""+EscaleList.getValueAt(x, 0));
            String heuredep = (String) EscaleList.getValueAt(x, 1);
            String heureArr = (String) EscaleList.getValueAt(x, 2);
            String AirportEs = (String) EscaleList.getValueAt(x, 3);

            
          
            datelbl.setText( heuredep);
            heureEs.setText(heureArr);
            TxtEscaleAirport.setText(AirportEs);

          
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton AddButn;
    private com.k33ptoo.components.KButton AddButn1;
    private javax.swing.JComboBox  TxtNameAirport;
    private javax.swing.JTextField TxtVolId;
    private javax.swing.JTextField TxtheuredepEscale ;
    private javax.swing.JComboBox TxtEscaleName;
    private javax.swing.JTextField TxtEscaleAirport;

    private javax.swing.JTextField TxtDdepVol;
    private javax.swing.JTextField TxtDArrVol;
    
    private javax.swing.JTextField datelbl;
    private javax.swing.JTextField heureEs;

    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel155;
 
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel199;
    private javax.swing.JLabel jLabell20;

    private javax.swing.JComboBox jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTable EscaleList;
    private javax.swing.JLabel totallbl;
    // End of variables declaration//GEN-END:variables

   
}
