/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.EscaleController;
import Controller.VolController;
import Model.Escale;
import Model.Vol;

import static java.time.zone.ZoneRulesProvider.refresh;

import java.awt.Color;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Iyed
 */
public class ShowVol extends javax.swing.JInternalFrame {

    /**
     * Creates new form ShowVol
     */
    public ShowVol() {
        initComponents();
         ArrayList<Vol>  myVollist = new VolController().retrieveAll();
        DefaultTableModel model = new DefaultTableModel() ;
        VolList.setModel(model) ; 
                    model.addColumn("IdVoL");
                    model.addColumn("nameAirport");
                    model.addColumn("nameAirportArr");
                    model.addColumn(" AerportEscale");
                    model.addColumn("DdepVol");
                    model.addColumn("DarrVol");
                    model.addColumn("heuredepEscale ");
                    model.addColumn("heureArrEscale");
                    model.addColumn("reservation");


                    for (Vol u : myVollist) {            
                        Object[] row =   new Object[]{u.getIdVol(),u.getNameAirport(),u.getNameAirportArr(),u.getAerportEscale(),
                        		                      u.getDdepVol(),u.getDarrVol(),u.getHeuredepEscale(),
                        		                      u.getHeureArrEscale(),u.getReservation()};
                        model.addRow(  row);
                    }
                    VolList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VolList = new javax.swing.JTable();
        Txtsearch = new javax.swing.JTextField();
        Search = new javax.swing.JLabel();
        DeleteButn = new com.k33ptoo.components.KButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkGradientFocus(900);
        kGradientPanel1.setkStartColor(new java.awt.Color(15, 95, 134));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vol List");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/delivery_service_45c25as3bdbd_64.png"))); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, -1, -1));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 120));

        VolList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(VolList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 880, 320));

        Txtsearch.setBackground(new Color (0,0,0,0));
        Txtsearch.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        Txtsearch.setForeground(new java.awt.Color(15, 95, 134));
        Txtsearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(15, 95, 134)));

        Txtsearch.setOpaque(false);
        jPanel1.add(Txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 310, 33));

        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/search_r3mpefxhd0uh_32.png"))); // NOI18N
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));
        DeleteButn.setText("Delete Escale");
        DeleteButn.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        DeleteButn.setkBorderRadius(50);
        DeleteButn.setkEndColor(new java.awt.Color(102, 204, 255));
        DeleteButn.setkHoverEndColor(new java.awt.Color(0, 102, 255));
        DeleteButn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        DeleteButn.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        DeleteButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButnActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteButn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, -1, -1));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/delete_user_px74wjrc8rn6_32.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 630, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
          String keyword= Txtsearch.getText();
        ArrayList<Vol>  myVollist = new VolController().retrieveByKeyWord(keyword);
            DefaultTableModel model = new DefaultTableModel() ;
        VolList.setModel(model) ; 
        model.addColumn("IdVoL");
        model.addColumn("nameAirport");
        model.addColumn("nameAirportArr");
        model.addColumn(" AerportEscale");
        model.addColumn("DdepVol");
        model.addColumn("DarrVol");
        model.addColumn("heuredepEscale ");
        model.addColumn("heureArrEscale");
        model.addColumn("reservation");

                    for (Vol u : myVollist) {            
                        Object[] row =   new Object[]{u.getIdVol(),u.getNameAirport(),u.getNameAirportArr(),u.getAerportEscale(),
  		                      u.getDdepVol(),u.getDarrVol(),u.getHeuredepEscale(),
  		                      u.getHeureArrEscale(),u.getReservation()};
                        model.addRow(  row);
                    }
                    VolList.setModel(model);
    }//GEN-LAST:event_SearchMouseClicked
    private void DeleteButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButnActionPerformed
    	   
        int x= VolList.getSelectedRow();
        if(x == -1){
             JOptionPane.showMessageDialog(this,
            "Select row please !",
            "Information Message", JOptionPane.INFORMATION_MESSAGE);
        } else{
            int p=  JOptionPane.showConfirmDialog(this,
            "Confirm to delete row number : "+ (x+1),
            "Information Message", JOptionPane.INFORMATION_MESSAGE);
             System.out.println(p);
             if (p == 0){
                 int id =  Integer.parseInt(""+VolList.getValueAt(x, 0));
                 System.out.println(id);
                 if(new VolController().delete(id)){
                      JOptionPane.showMessageDialog(this,
            "Escale Deleted with success!",
            "Information Message", JOptionPane.INFORMATION_MESSAGE);
                      
                      
                    ArrayList<Vol>  myVolList = new VolController().retrieveAll();
                    DefaultTableModel model = new DefaultTableModel() ;
                    VolList.setModel(model) ; 
                    model.addColumn("IdVoL");
                    model.addColumn("nameAirport");
                    model.addColumn("nameAirportArr");
                    model.addColumn("AerportEscale");
                    model.addColumn("DdepVol");
                    model.addColumn("DarrVol");
                    model.addColumn("heuredepEscale ");
                    model.addColumn("heureArrEscale");
                    model.addColumn("reservation");


                    for (Vol u : myVolList) {            
                        Object[] row =   new Object[]{u.getIdVol(),u.getNameAirport(),u.getNameAirportArr(),u.getAerportEscale(),
    		                      u.getDdepVol(),u.getDarrVol(),u.getHeuredepEscale(),
      		                      u.getHeureArrEscale(),u.getReservation()};
                            model.addRow(  row);
                        
                    }
                    VolList.setModel(model);

                      refresh();
                      
                      
                 } else{
                      JOptionPane.showMessageDialog(this,
            "Escale not Deleted check with the administrator!",
            "Error Message", JOptionPane.ERROR_MESSAGE);
                 }
                 
             }
             
        } refresh();}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable VolList;
    private javax.swing.JLabel Search;
    private javax.swing.JTextField Txtsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KButton DeleteButn;

    // End of variables declaration//GEN-END:variables
}
