/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controller.AirportController;
import Model.Airport;
import static View.Login.isAdmin;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Iyed
 */
public class ShowAirports extends javax.swing.JInternalFrame {

    /**
     * Creates new form ShowAirports
     */
    public ShowAirports() {
        initComponents();
        Txtid.setEditable(false);
                 if (!isAdmin )
         {
             AddButn.setEnabled(false);
             ModifyButn.setEnabled(false);
             DeleteButn.setEnabled(false);
         }
       ArrayList<Airport>  myAirportist = new AirportController().retrieveAll();
        DefaultTableModel model = new DefaultTableModel() ;
        jTable1.setModel(model) ; 
        model.addColumn("id");
        model.addColumn("NameAirport");
        model.addColumn("PaysAirport");
      

        for (Airport c  : myAirportist) {            
            Object[] row =   new Object[]{c.getId(), c.getNameAirport(),c.getPaysAirport()};
            model.addRow(  row);
        }
        jTable1.setModel(model);
    }
    public void refresh()
    {
        Txtid.setText("");
        TxtNameAirport.setText("");
        TxtPaysAirport.setText("");
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        Txtsearch = new javax.swing.JTextField();
        Search = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AddButn = new com.k33ptoo.components.KButton();
        DeleteButn = new com.k33ptoo.components.KButton();
        ModifyButn = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        Txtid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtPaysAirport = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtNameAirport = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkGradientFocus(900);
        kGradientPanel1.setkStartColor(new java.awt.Color(15, 95, 134));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Txtsearch.setBackground(new Color (0,0,0,0));
        Txtsearch.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        Txtsearch.setForeground(new java.awt.Color(255, 255, 255));
        Txtsearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        Txtsearch.setOpaque(false);
        kGradientPanel1.add(Txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 310, 33));

        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/search.png"))); // NOI18N
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
        });
        kGradientPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/target_xd3gln9dyu7c_64.png"))); // NOI18N
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, -1, -1));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 110));

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Airport List");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        AddButn.setText("Add New Airport");
        AddButn.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        AddButn.setkBorderRadius(50);
        AddButn.setkEndColor(new java.awt.Color(102, 204, 255));
        AddButn.setkHoverEndColor(new java.awt.Color(0, 102, 255));
        AddButn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        AddButn.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        AddButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButnActionPerformed(evt);
            }
        });
        jPanel1.add(AddButn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, -1, -1));

        DeleteButn.setText("Delete Airport");
        DeleteButn.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        DeleteButn.setkBorderRadius(50);
        DeleteButn.setkEndColor(new java.awt.Color(102, 204, 255));
        DeleteButn.setkHoverEndColor(new java.awt.Color(0, 102, 255));
        DeleteButn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        DeleteButn.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        
        DeleteButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButnActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteButn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, -1, -1));

        ModifyButn.setText("Modify Airport");
        ModifyButn.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        ModifyButn.setkBorderRadius(50);
        ModifyButn.setkEndColor(new java.awt.Color(102, 204, 255));
        ModifyButn.setkHoverEndColor(new java.awt.Color(0, 102, 255));
        ModifyButn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        ModifyButn.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        
        ModifyButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButnActionPerformed(evt);
            }
        });
        jPanel1.add(ModifyButn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, -1, -1));
        jTable1.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(153, 204, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 530, 380));

        kGradientPanel2.setkBorderRadius(50);
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkFillBackground(false);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 153, 153));
        kGradientPanel2.setOpaque(false);
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Txtid.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        Txtid.setForeground(new java.awt.Color(204, 0, 102));
        
        Txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtidActionPerformed(evt);
            }
        });
        kGradientPanel2.add(Txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 260, 30));

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Pays Airport  : ");
        kGradientPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        TxtPaysAirport.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        TxtPaysAirport.setForeground(new java.awt.Color(204, 0, 102));
        
        TxtPaysAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPaysAirportActionPerformed(evt);
            }
        });
        kGradientPanel2.add(TxtPaysAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 260, 30));

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("ID : ");
        kGradientPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Name Airport  : ");
        kGradientPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        TxtNameAirport.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        TxtNameAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNameAirportActionPerformed(evt);
            }
        });
        kGradientPanel2.add(TxtNameAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 260, 30));

        jPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 380, 270));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/compose_v8rchwj06sxy_32.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 630, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/delete_user_px74wjrc8rn6_32.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 560, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/add_user_dhb2qcoc65n2_32.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents
// button rechercheee
    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
    String keyword= Txtsearch.getText();
        ArrayList<Airport>  myAirportist = new AirportController().retrieveByKeyWord(keyword);
        DefaultTableModel model = new DefaultTableModel() ;
        jTable1.setModel(model) ; 
        model.addColumn("id");
        model.addColumn("NameAirport");
        model.addColumn("PaysAirport");


        for (Airport c : myAirportist) {            
            Object[] row =   new Object[]{c.getId(), c.getNameAirport(), c.getPaysAirport() };
            model.addRow(  row);
        }
        jTable1.setModel(model);
    }//GEN-LAST:event_SearchMouseClicked
// ajouterrr
    private void AddButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButnActionPerformed

          if (isAdmin == false)
         {
           JOptionPane.showMessageDialog(this,
            "Sorry ! Only Admin Can do this !");
         }else{
        Airport Airport = new Airport();
        Airport.setNameAirport(TxtNameAirport.getText());
        Airport.setPaysAirport(TxtPaysAirport.getText());
      
 
        boolean result = new AirportController().create(Airport);
        
         if(result){              
            JOptionPane.showMessageDialog(this,
            Airport.getNameAirport().toUpperCase()+" Is successfuly added  ",
            "New Airport", JOptionPane.INFORMATION_MESSAGE);
           
                    ArrayList<Airport>  myAirportist = new AirportController().retrieveAll();
                    DefaultTableModel model = new DefaultTableModel() ;
                    jTable1.setModel(model) ; 
                    model.addColumn("id");
                    model.addColumn("NameAirport");
                    model.addColumn("PaysAirport");
                    

                    for (Airport c : myAirportist) {            
                        Object[] row =   new Object[]{c.getId(), c.getNameAirport(),c.getPaysAirport()};
                        model.addRow(row);
                    }
                    jTable1.setModel(model);
            
            
            
        }else{          
            JOptionPane.showMessageDialog(this,
            "Ajout erronée ",
            "Nouveau Airport", JOptionPane.ERROR_MESSAGE);
        }
         refresh();}
    }//GEN-LAST:event_AddButnActionPerformed
//suppprimer
    private void DeleteButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButnActionPerformed
          if (isAdmin == false)
         {
                         JOptionPane.showMessageDialog(this,
            "Sorry ! Only Admin Can do this !");
         }else{
        int x= jTable1.getSelectedRow();
        if(x == -1){
             JOptionPane.showMessageDialog(this,
            "Select row please !",
            "Information Message", JOptionPane.INFORMATION_MESSAGE);
        } else{
            int p=  JOptionPane.showConfirmDialog(this,
            "Confirm to delete row number : "+ (x+1),
            "Information Message", JOptionPane.INFORMATION_MESSAGE);
             System.out.println(p);
             if (p == 0){
                 int id =  Integer.parseInt(""+jTable1.getValueAt(x, 0));
                 System.out.println(id);
                 if(new AirportController().delete(id)){
                      JOptionPane.showMessageDialog(this,
            "Airport  Deleted with success!",
            "Information Message", JOptionPane.INFORMATION_MESSAGE);
                      
                      
                    ArrayList<Airport>  myAirportist = new AirportController().retrieveAll();
                    DefaultTableModel model = new DefaultTableModel() ;
                    jTable1.setModel(model) ; 
                    model.addColumn("id");
                    model.addColumn("NameAirport");
                    model.addColumn("PaysAirport");


                    for (Airport c : myAirportist) {            
                        Object[] row =   new Object[]{c.getId(), c.getNameAirport(), c.getPaysAirport()};
                        model.addRow(  row);
                    }
                    jTable1.setModel(model);

                    
                      
                      
                 } else{
                      JOptionPane.showMessageDialog(this,
            "Airport not Deleted check with the administrator!",
            "Error Message", JOptionPane.ERROR_MESSAGE);
                 }
                 
             }
               
        } refresh();}
    }//GEN-LAST:event_DeleteButnActionPerformed
//modifirrrrrr
    private void ModifyButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButnActionPerformed
         if (isAdmin == false)
         {
                         JOptionPane.showMessageDialog(this,
            "Sorry ! Only Admin Can do this !");
         }else{
        Airport Airport = new Airport();
        Airport.setNameAirport(TxtNameAirport.getText());
        Airport.setPaysAirport(TxtPaysAirport.getText());
        
 
        
        int id = Integer.parseInt(""+ Txtid.getText());
        boolean result = new AirportController().update(id, Airport);
        
         if(result){              
            JOptionPane.showMessageDialog(this,
            Airport.getNameAirport().toUpperCase()+" est modifié avec success ",
            "Modifier utilisateur", JOptionPane.INFORMATION_MESSAGE);
            //new userList().setVisible(true);
                    ArrayList<Airport>  myAirportist = new AirportController().retrieveAll();
                    DefaultTableModel model = new DefaultTableModel() ;
                    jTable1.setModel(model) ; 
                    model.addColumn("id");
                    model.addColumn("nameAirport");
                    model.addColumn("paysAirport");
               

                    for (Airport c : myAirportist) {            
                        Object[] row =   new Object[]{c.getId(), c.getNameAirport(), c.getPaysAirport()};
                        model.addRow(  row);
                    }
                    jTable1.setModel(model);
          
        }else{          
            JOptionPane.showMessageDialog(this,
            "Modification erronée ",
            "Modifier Airport", JOptionPane.ERROR_MESSAGE);
        }
         refresh();}
    }//GEN-LAST:event_ModifyButnActionPerformed

    private void TxtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtidActionPerformed
        
    }//GEN-LAST:event_TxtidActionPerformed

    private void TxtPaysAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPaysAirportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPaysAirportActionPerformed

    private void TxtNameAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNameAirportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNameAirportActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
                       int x= jTable1.getSelectedRow();
        if(x == -1){
             JOptionPane.showMessageDialog(this,
            "Select row please !",
            "Information Message", JOptionPane.INFORMATION_MESSAGE);
        } else{

                int id = Integer.parseInt(""+jTable1.getValueAt(x, 0));
                String NameAirport = (String) jTable1.getValueAt(x, 1);
                String  PaysAirport = (String) jTable1.getValueAt(x, 2);
              
                 Txtid.setText(String.valueOf(id));
                 Txtid.setEnabled(false);
                 TxtNameAirport.setText(NameAirport);
                 TxtPaysAirport.setText(String.valueOf(PaysAirport));
                 
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton AddButn;
    private com.k33ptoo.components.KButton DeleteButn;
    private com.k33ptoo.components.KButton ModifyButn;
    private javax.swing.JLabel Search;
    private javax.swing.JTextField Txtid;
    private javax.swing.JTextField TxtNameAirport;
    private javax.swing.JTextField TxtPaysAirport;
    private javax.swing.JTextField Txtsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
